version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: npm run dev -- -p ${PORT_FRONTEND}
    ports: 
      - ${PORT_FRONTEND}:${PORT_FRONTEND}
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend:rw
      - ./frontend/front_dist:/frontend/front_dist:rw
      - /frontend/node_modules
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
      - ${PORT_BACKEND}:${PORT_BACKEND}
    restart: unless-stopped
    command: nodemon app.js
    volumes:
      - ./backend:/backend:rw
      - ./backend/dist:/backend/dist:rw
      - /backend/node_modules
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      JWT_SECRET: "${JWT_SECRET}"
      ENC_PASS: "${ENC_PASS}"
      APP_USER: "${APP_USER}"
      APP_PASS: "${APP_PASS}"
      DB_SERVICE_NAME: "db"
      PORT_BACKEND: "${PORT_BACKEND}"

  db:
    image: mongo:latest
    ports:
      # 27018 for mongodb compass
      - 27018:27017
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_DATABASE: "${DB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    logging:
      driver: "none"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    environment:
      PORT_FRONTEND: ${PORT_FRONTEND}
      PORT_BACKEND: ${PORT_BACKEND}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx

    restart: unless-stopped
    volumes:
      - ./nginx/dev:/etc/nginx/templates
      - ./static:/static:rw
      - ./frontend/front_dist:/front_dist
    logging:
      driver: none

volumes:
  mongodb_data_container: