version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: npm run dev
    ports: 
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/frontend:rw
      - ./frontend/front_dist:/frontend/front_dist:rw
      - /frontend/node_modules
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
      - 3010:3010
    restart: always
    command: nodemon app.js
    volumes:
      - ./backend:/backend:rw
      - ./backend/dist:/backend/dist:rw
      - /backend/node_modules
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      JWT_SECRET: "${JWT_SECRET}"
      DB_SERVICE_NAME: "db"

  db:
    image: mongo:latest
    ports:
      # 27018 for mongodb compass
      - 27018:27017
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_DATABASE: "${DB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    logging:
      driver: "none"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static:rw
      - ./frontend/front_dist:/front_dist
    logging:
      driver: none

volumes:
  mongodb_data_container: